Upgrade to API v2
coletiv/coletiv-ios-swiftui-tca-example pull request #1
Opened 2021-08-02 08:53 UTC by dfalmeida

## Description
- Updated API to v2
- Updated packages dependencies to latest versions
- Updated README

2021-11-22 12:00 UTC, andreragsilva requested changes
@dfalmeida it also appears you changed the snapshot test screenshots by lowering the resolution. Was the high resolution affecting testing? This may affect the level of interface testing we have in terms of pixel perfect hence the curiosity 🤔

2021-11-22 12:00 UTC, andreragsilva commented on PokemonCards/Application/Cards/CardsCore.swift
> +        print(error)
Should we keep debug code? 🤔

2021-11-22 12:01 UTC, andreragsilva commented
> @dfalmeida it also appears you changed the snapshot test screenshots by lowering the resolution. Was the high resolution affecting testing? This may affect the level of interface testing we have in terms of pixel perfect hence the curiosity 🤔

Also, tests are failing as you mentioned before, just leaving a heads up 👍

2021-11-26 18:18 UTC, andreragsilva commented
@dfalmeida CI is still failing 🤔  So I will wait till there is time to fix it so I can review once again 👍

2021-12-14 02:18 UTC, andreragsilva commented
@dfalmeida CI still failing so I will postpone my review once again, hope you are able to close this 💪 Let me know if you need help

2022-01-21 17:32 UTC, dfalmeida commented on PokemonCards/Application/Cards/CardsCore.swift
> +        print(error)
Sure not! 😓

2022-01-21 17:33 UTC, dfalmeida commented
> @dfalmeida it also appears you changed the snapshot test screenshots by lowering the resolution. Was the high resolution affecting testing? This may affect the level of interface testing we have in terms of pixel perfect hence the curiosity 🤔

I changed the test device to a smaller one, maybe that was the cause 🤔

2022-01-21 17:39 UTC, dfalmeida commented
@andreragsilva just disabled the snapshot testing on CI. It is something that needs a deeper investigation. 
As far as I understood, the CI machines generates a pixelated snapshot that doesn't match the original one, I tried everything I could: 
* Changed to a different macOS version
* Changed the snapshot strategy
* Find a way to change the graphic requirements from the machine. Cannot find those settings ofc :/ 

In the end CI is green 🍏😑

2022-01-21 19:07 UTC, andreragsilva approved these changes
@dfalmeida lets close this, I believe when and if we pick this up again, a lot will have change so we will be able to find an easier path (hopefully) 👍

Great work anyway, hope you enjoyed it 💪

2022-07-14 17:22 UTC, merged